### PR TITLE
(GH-32) Transitions to module-based tooling

### LINKED ISSUE #32: Create framework for a module
To make this something we can put on the Gallery, this should be a module.

### PR DESCRIPTION
**Pull request by steviecoaster**
This PR includes a lot of code fix-ups that turns the codebase into a working powershell module. 
Please review the changes I have made and let me know any additional changes that you'd like to see made. 

Closes #32 

Note: This probably _does_ break some things in the interim as we work out a couple of things, but that will require some discussion, which I am happy to spearhead. This is a great tool, and happy to do my small part!

### CODE REVIEW

**Comment by compwiz32** [comment]
nice!

**Comment by dohminion** [comment]
Did you test them yet?

I was going to try to get time tomorrow to see if a scheduled task can directly call a function.  Not sure what profile would load the module into memory to do that...

Worst case we build a new script for the scheduled task to call it. Basically just two lines, import the module and run the line that he commented out. :)

**Comment by compwiz32** [comment]
I was thinking the same thing about the function... A script that is
basically a one-liner...

No i didnt test yet.

Mike Kanakos
mkanakos@gmail.com

**Comment by steviecoaster** [comment]
Doesn't even need to be a script. -Command ipmo PSADHealth ; Function does
the trick.

**Pull request merged**
